### PR TITLE
updated evolve.py

### PR DESCRIPTION
**Pull request by yampelo**
The script wouldn't work because the eVOLve.htm was in uppercase VOL which gave you a 404 when running it

### CODE REVIEW

**Comment by JamesHabben** [comment]
Good find on the mixed case. 

I don't like the hard coded path that you have, though. That is very specific to Linux systems. It would work on OS X, but it is not a common location. And of course that path doesn't exist on a Windows machine.

This is the reason why I chose to put the sqlite file beside the ram dump. That path will always exist. What is your thought for storing all of the databases in a single location?

**Comment by yampelo** [comment]
Maybe detect OS and send the database files the usr/local/bin/evolve/databases if on linux. Currently if the memory dump files are on a NFS / Samba share it's impossible to use the tool beacuse the sqllite db gets locked.

I think the naming should also be done via the md5 hashing of the contents of the file because if the contents of the memory dump changed it's probably a different set of memory.

**Comment by JamesHabben** [comment]
Found this regarding this issue:
http://stackoverflow.com/questions/9907429/locking-sqlite-file-on-nfs-filesystem-possible#answers-header

Do not put SQLite on NFS. :)

**Comment by yampelo** [comment]
Yeah it looks like it just doesn't work with network shares

**Comment by JamesHabben** [comment]
What do you think about adding a parameter input to specify an output path? Maybe also an option to store the db in a central location coded into the source?
`-o --outputpath Specify a folder location to place the SQLite db file`
`-c --central Use this option to store the SQLite db in a central location (/usr/bin/local/evolve/db or %appdata%\evolve\db)`

I want to avoid storing the db in some central location automatically because I plan to add portability to this. Basically allow someone to run a bunch of the plugins to dump data into the sqlite file, and then give evolve with the sqlite file only to another examiner to review the data.

**Comment by yampelo** [comment]
Sounds good, 

As long as theres a way to save them locally and not in the same directory

**Comment by yampelo** [comment]
I found a fix, if you mount the nfs share with the 'nolock' option it'll work, might wanna put that in the readme

**Comment by JamesHabben** [comment]
Added a note to the usage section. Thanks for the find.

**Comment by JamesHabben** [comment]
I added the output path option, so I will close this pull request. Please post more if you find problems!

**Pull request closed without merging**
